import type { AbilityDefinition } from '../types/ability';

export const ABILITIES: Record<string, AbilityDefinition> = {
  // =============================================================================
  // IRONCLAD - Tank
  // =============================================================================
  ironclad_q: {
    id: 'ironclad_q',
    name: 'Shield Bash',
    description: 'Slams shield into target, dealing damage and stunning briefly.',
    slot: 'Q',
    targetType: 'unit',
    damageType: 'physical',
    manaCost: [40, 45, 50, 55, 60],
    cooldown: [8, 7.5, 7, 6.5, 6],
    castTime: 0.2,
    range: 200,
    baseDamage: [60, 100, 140, 180, 220],
    scalingAD: 0.6,
    iconPath: '/assets/abilities/ironclad_q.webp',
  },
  ironclad_w: {
    id: 'ironclad_w',
    name: 'Iron Fortress',
    description: 'Raises shield, blocking damage and reducing incoming damage for a duration.',
    slot: 'W',
    targetType: 'self',
    damageType: null,
    manaCost: [50, 55, 60, 65, 70],
    cooldown: [14, 13, 12, 11, 10],
    castTime: 0,
    range: 0,
    iconPath: '/assets/abilities/ironclad_w.webp',
  },
  ironclad_e: {
    id: 'ironclad_e',
    name: 'Charge',
    description: 'Charges forward, knocking aside enemies and stopping at first champion hit.',
    slot: 'E',
    targetType: 'direction',
    damageType: 'physical',
    manaCost: [60, 60, 60, 60, 60],
    cooldown: [12, 11, 10, 9, 8],
    castTime: 0.1,
    range: 600,
    baseDamage: [70, 110, 150, 190, 230],
    scalingAD: 0.5,
    iconPath: '/assets/abilities/ironclad_e.webp',
  },
  ironclad_r: {
    id: 'ironclad_r',
    name: 'Unbreakable Will',
    description: 'Becomes immune to crowd control and gains massive armor for 5 seconds.',
    slot: 'R',
    targetType: 'self',
    damageType: null,
    manaCost: [100, 100, 100],
    cooldown: [120, 100, 80],
    castTime: 0,
    range: 0,
    iconPath: '/assets/abilities/ironclad_r.webp',
  },

  // =============================================================================
  // PYRALIS - Mage
  // =============================================================================
  pyralis_q: {
    id: 'pyralis_q',
    name: 'Fireball',
    description: 'Hurls a fireball that explodes on impact, dealing area damage.',
    slot: 'Q',
    targetType: 'point',
    damageType: 'magical',
    manaCost: [60, 65, 70, 75, 80],
    cooldown: [6, 5.5, 5, 4.5, 4],
    castTime: 0.3,
    range: 800,
    radius: 200,
    baseDamage: [80, 130, 180, 230, 280],
    scalingAP: 0.75,
    iconPath: '/assets/abilities/pyralis_q.webp',
  },
  pyralis_w: {
    id: 'pyralis_w',
    name: 'Flame Wave',
    description: 'Sends a wave of fire in a cone, burning enemies over time.',
    slot: 'W',
    targetType: 'direction',
    damageType: 'magical',
    manaCost: [70, 80, 90, 100, 110],
    cooldown: [10, 9, 8, 7, 6],
    castTime: 0.2,
    range: 500,
    radius: 300,
    baseDamage: [60, 100, 140, 180, 220],
    scalingAP: 0.5,
    iconPath: '/assets/abilities/pyralis_w.webp',
  },
  pyralis_e: {
    id: 'pyralis_e',
    name: 'Blazing Dash',
    description: 'Transforms into flames and dashes, leaving a fire trail.',
    slot: 'E',
    targetType: 'direction',
    damageType: 'magical',
    manaCost: [50, 50, 50, 50, 50],
    cooldown: [14, 13, 12, 11, 10],
    castTime: 0,
    range: 450,
    baseDamage: [50, 80, 110, 140, 170],
    scalingAP: 0.3,
    iconPath: '/assets/abilities/pyralis_e.webp',
  },
  pyralis_r: {
    id: 'pyralis_r',
    name: 'Inferno',
    description: 'Channels a massive firestorm in target area, dealing devastating damage.',
    slot: 'R',
    targetType: 'area',
    damageType: 'magical',
    manaCost: [100, 100, 100],
    cooldown: [120, 100, 80],
    castTime: 1.0,
    range: 700,
    radius: 400,
    baseDamage: [250, 400, 550],
    scalingAP: 1.0,
    iconPath: '/assets/abilities/pyralis_r.webp',
  },

  // =============================================================================
  // BLADEWARDEN - Warrior
  // =============================================================================
  bladewarden_q: {
    id: 'bladewarden_q',
    name: 'Swift Strike',
    description: 'Dashes to target and strikes, dealing damage based on attack damage.',
    slot: 'Q',
    targetType: 'unit',
    damageType: 'physical',
    manaCost: [30, 35, 40, 45, 50],
    cooldown: [5, 4.5, 4, 3.5, 3],
    castTime: 0,
    range: 400,
    baseDamage: [20, 40, 60, 80, 100],
    scalingAD: 1.0,
    iconPath: '/assets/abilities/bladewarden_q.webp',
  },
  bladewarden_w: {
    id: 'bladewarden_w',
    name: 'Blade Dance',
    description: 'Spins with both blades, hitting all nearby enemies multiple times.',
    slot: 'W',
    targetType: 'self',
    damageType: 'physical',
    manaCost: [50, 55, 60, 65, 70],
    cooldown: [10, 9, 8, 7, 6],
    castTime: 0,
    range: 0,
    radius: 300,
    baseDamage: [30, 55, 80, 105, 130],
    scalingAD: 0.4,
    iconPath: '/assets/abilities/bladewarden_w.webp',
  },
  bladewarden_e: {
    id: 'bladewarden_e',
    name: 'Parry',
    description: 'Enters defensive stance, blocking next attack and counter-striking.',
    slot: 'E',
    targetType: 'self',
    damageType: 'physical',
    manaCost: [40, 40, 40, 40, 40],
    cooldown: [16, 14, 12, 10, 8],
    castTime: 0,
    range: 0,
    baseDamage: [80, 120, 160, 200, 240],
    scalingAD: 0.8,
    iconPath: '/assets/abilities/bladewarden_e.webp',
  },
  bladewarden_r: {
    id: 'bladewarden_r',
    name: 'Storm of Steel',
    description: 'Becomes a whirlwind of blades, gaining attack speed and movement speed.',
    slot: 'R',
    targetType: 'self',
    damageType: null,
    manaCost: [100, 100, 100],
    cooldown: [100, 85, 70],
    castTime: 0,
    range: 0,
    iconPath: '/assets/abilities/bladewarden_r.webp',
  },

  // =============================================================================
  // SYLARA - Healer
  // =============================================================================
  sylara_q: {
    id: 'sylara_q',
    name: 'Healing Light',
    description: 'Sends a bolt of healing energy to target ally, restoring health.',
    slot: 'Q',
    targetType: 'unit',
    damageType: null,
    manaCost: [50, 55, 60, 65, 70],
    cooldown: [4, 3.5, 3, 2.5, 2],
    castTime: 0.2,
    range: 700,
    baseDamage: [60, 100, 140, 180, 220], // Actually healing
    scalingAP: 0.6,
    iconPath: '/assets/abilities/sylara_q.webp',
  },
  sylara_w: {
    id: 'sylara_w',
    name: 'Purifying Aura',
    description: 'Creates an aura that heals allies over time and damages enemies.',
    slot: 'W',
    targetType: 'self',
    damageType: 'magical',
    manaCost: [60, 70, 80, 90, 100],
    cooldown: [18, 16, 14, 12, 10],
    castTime: 0,
    range: 0,
    radius: 400,
    baseDamage: [20, 35, 50, 65, 80],
    scalingAP: 0.2,
    iconPath: '/assets/abilities/sylara_w.webp',
  },
  sylara_e: {
    id: 'sylara_e',
    name: 'Nature\'s Grasp',
    description: 'Roots target enemy in place with vines, dealing damage over time.',
    slot: 'E',
    targetType: 'unit',
    damageType: 'magical',
    manaCost: [70, 75, 80, 85, 90],
    cooldown: [14, 13, 12, 11, 10],
    castTime: 0.3,
    range: 600,
    baseDamage: [60, 100, 140, 180, 220],
    scalingAP: 0.5,
    iconPath: '/assets/abilities/sylara_e.webp',
  },
  sylara_r: {
    id: 'sylara_r',
    name: 'Tree of Life',
    description: 'Summons a sacred tree that massively heals all nearby allies over time.',
    slot: 'R',
    targetType: 'point',
    damageType: null,
    manaCost: [100, 100, 100],
    cooldown: [140, 120, 100],
    castTime: 0.5,
    range: 800,
    radius: 500,
    baseDamage: [150, 250, 350], // Actually healing per second
    scalingAP: 0.4,
    iconPath: '/assets/abilities/sylara_r.webp',
  },

  // =============================================================================
  // NIGHTSHADE - Assassin (Mystical)
  // =============================================================================
  nightshade_q: {
    id: 'nightshade_q',
    name: 'Shadow Strike',
    description: 'Blinks behind target enemy and strikes, dealing bonus damage from behind.',
    slot: 'Q',
    targetType: 'unit',
    damageType: 'physical',
    manaCost: [40, 45, 50, 55, 60],
    cooldown: [6, 5.5, 5, 4.5, 4],
    castTime: 0,
    range: 500,
    baseDamage: [50, 85, 120, 155, 190],
    scalingAD: 0.9,
    iconPath: '/assets/abilities/nightshade_q.webp',
  },
  nightshade_w: {
    id: 'nightshade_w',
    name: 'Cloak of Shadows',
    description: 'Becomes invisible for a short duration. Next attack deals bonus damage.',
    slot: 'W',
    targetType: 'self',
    damageType: null,
    manaCost: [60, 60, 60, 60, 60],
    cooldown: [18, 16, 14, 12, 10],
    castTime: 0,
    range: 0,
    iconPath: '/assets/abilities/nightshade_w.webp',
  },
  nightshade_e: {
    id: 'nightshade_e',
    name: 'Fan of Knives',
    description: 'Throws knives in a cone, damaging and slowing all enemies hit.',
    slot: 'E',
    targetType: 'direction',
    damageType: 'physical',
    manaCost: [50, 55, 60, 65, 70],
    cooldown: [10, 9, 8, 7, 6],
    castTime: 0.1,
    range: 400,
    radius: 250,
    baseDamage: [60, 95, 130, 165, 200],
    scalingAD: 0.6,
    iconPath: '/assets/abilities/nightshade_e.webp',
  },
  nightshade_r: {
    id: 'nightshade_r',
    name: 'Death Mark',
    description: 'Marks target for death. After 3 seconds, deals massive damage based on damage dealt during mark.',
    slot: 'R',
    targetType: 'unit',
    damageType: 'physical',
    manaCost: [100, 100, 100],
    cooldown: [120, 100, 80],
    castTime: 0,
    range: 450,
    baseDamage: [200, 300, 400],
    scalingAD: 1.5,
    iconPath: '/assets/abilities/nightshade_r.webp',
  },

  // =============================================================================
  // VEX - Assassin (Human)
  // =============================================================================
  vex_q: {
    id: 'vex_q',
    name: 'Poison Dagger',
    description: 'Throws a poisoned dagger that deals initial damage and poison over time.',
    slot: 'Q',
    targetType: 'unit',
    damageType: 'physical',
    manaCost: [35, 40, 45, 50, 55],
    cooldown: [5, 4.5, 4, 3.5, 3],
    castTime: 0.1,
    range: 550,
    baseDamage: [40, 70, 100, 130, 160],
    scalingAD: 0.7,
    iconPath: '/assets/abilities/vex_q.webp',
  },
  vex_w: {
    id: 'vex_w',
    name: 'Acrobatic Dodge',
    description: 'Performs an evasive flip, becoming untargetable briefly and gaining attack speed.',
    slot: 'W',
    targetType: 'direction',
    damageType: null,
    manaCost: [50, 50, 50, 50, 50],
    cooldown: [14, 13, 12, 11, 10],
    castTime: 0,
    range: 350,
    iconPath: '/assets/abilities/vex_w.webp',
  },
  vex_e: {
    id: 'vex_e',
    name: 'Crippling Strike',
    description: 'Slashes enemy tendons, dealing damage and reducing their movement speed drastically.',
    slot: 'E',
    targetType: 'unit',
    damageType: 'physical',
    manaCost: [60, 65, 70, 75, 80],
    cooldown: [12, 11, 10, 9, 8],
    castTime: 0,
    range: 200,
    baseDamage: [70, 110, 150, 190, 230],
    scalingAD: 0.8,
    iconPath: '/assets/abilities/vex_e.webp',
  },
  vex_r: {
    id: 'vex_r',
    name: 'Deadly Pursuit',
    description: 'Gains massive movement speed and resets Q cooldown on kill for 8 seconds.',
    slot: 'R',
    targetType: 'self',
    damageType: null,
    manaCost: [100, 100, 100],
    cooldown: [110, 95, 80],
    castTime: 0,
    range: 0,
    iconPath: '/assets/abilities/vex_r.webp',
  },

  // =============================================================================
  // THORNWEAVER - Tank (Mystical)
  // =============================================================================
  thornweaver_q: {
    id: 'thornweaver_q',
    name: 'Thorn Lash',
    description: 'Extends thorny vines to strike and pull enemy closer.',
    slot: 'Q',
    targetType: 'unit',
    damageType: 'physical',
    manaCost: [45, 50, 55, 60, 65],
    cooldown: [9, 8, 7, 6, 5],
    castTime: 0.2,
    range: 600,
    baseDamage: [50, 90, 130, 170, 210],
    scalingAD: 0.5,
    iconPath: '/assets/abilities/thornweaver_q.webp',
  },
  thornweaver_w: {
    id: 'thornweaver_w',
    name: 'Bark Shield',
    description: 'Hardens bark exterior, gaining a shield and reflecting damage to attackers.',
    slot: 'W',
    targetType: 'self',
    damageType: null,
    manaCost: [60, 65, 70, 75, 80],
    cooldown: [16, 15, 14, 13, 12],
    castTime: 0,
    range: 0,
    iconPath: '/assets/abilities/thornweaver_w.webp',
  },
  thornweaver_e: {
    id: 'thornweaver_e',
    name: 'Entangling Roots',
    description: 'Causes roots to erupt from the ground, rooting enemies in an area.',
    slot: 'E',
    targetType: 'area',
    damageType: 'magical',
    manaCost: [70, 75, 80, 85, 90],
    cooldown: [14, 13, 12, 11, 10],
    castTime: 0.3,
    range: 700,
    radius: 300,
    baseDamage: [60, 100, 140, 180, 220],
    scalingAP: 0.4,
    iconPath: '/assets/abilities/thornweaver_e.webp',
  },
  thornweaver_r: {
    id: 'thornweaver_r',
    name: 'Nature\'s Wrath',
    description: 'Transforms into a massive treant, gaining size, health, and thorns damage.',
    slot: 'R',
    targetType: 'self',
    damageType: null,
    manaCost: [100, 100, 100],
    cooldown: [130, 110, 90],
    castTime: 0.5,
    range: 0,
    iconPath: '/assets/abilities/thornweaver_r.webp',
  },

  // =============================================================================
  // MAGNUS - Mage (Human)
  // =============================================================================
  magnus_q: {
    id: 'magnus_q',
    name: 'Gravity Bolt',
    description: 'Fires a bolt of condensed gravity that damages and slows the target.',
    slot: 'Q',
    targetType: 'unit',
    damageType: 'magical',
    manaCost: [55, 60, 65, 70, 75],
    cooldown: [7, 6.5, 6, 5.5, 5],
    castTime: 0.25,
    range: 700,
    baseDamage: [70, 115, 160, 205, 250],
    scalingAP: 0.7,
    iconPath: '/assets/abilities/magnus_q.webp',
  },
  magnus_w: {
    id: 'magnus_w',
    name: 'Gravitational Field',
    description: 'Creates a field that slows enemies and increases ally movement speed.',
    slot: 'W',
    targetType: 'area',
    damageType: null,
    manaCost: [70, 80, 90, 100, 110],
    cooldown: [18, 17, 16, 15, 14],
    castTime: 0.2,
    range: 800,
    radius: 350,
    iconPath: '/assets/abilities/magnus_w.webp',
  },
  magnus_e: {
    id: 'magnus_e',
    name: 'Repulse',
    description: 'Reverses gravity around self, pushing away and damaging all nearby enemies.',
    slot: 'E',
    targetType: 'self',
    damageType: 'magical',
    manaCost: [60, 65, 70, 75, 80],
    cooldown: [12, 11, 10, 9, 8],
    castTime: 0,
    range: 0,
    radius: 400,
    baseDamage: [80, 120, 160, 200, 240],
    scalingAP: 0.5,
    iconPath: '/assets/abilities/magnus_e.webp',
  },
  magnus_r: {
    id: 'magnus_r',
    name: 'Singularity',
    description: 'Creates a black hole that pulls in enemies and deals massive damage.',
    slot: 'R',
    targetType: 'area',
    damageType: 'magical',
    manaCost: [100, 100, 100],
    cooldown: [130, 110, 90],
    castTime: 0.5,
    range: 800,
    radius: 450,
    baseDamage: [200, 325, 450],
    scalingAP: 0.9,
    iconPath: '/assets/abilities/magnus_r.webp',
  },

  // =============================================================================
  // FROSTBORNE - Mage (Mystical)
  // =============================================================================
  frostborne_q: {
    id: 'frostborne_q',
    name: 'Ice Shard',
    description: 'Hurls a piercing shard of ice that damages and chills enemies.',
    slot: 'Q',
    targetType: 'direction',
    damageType: 'magical',
    manaCost: [50, 55, 60, 65, 70],
    cooldown: [5, 4.5, 4, 3.5, 3],
    castTime: 0.2,
    range: 900,
    baseDamage: [60, 100, 140, 180, 220],
    scalingAP: 0.65,
    iconPath: '/assets/abilities/frostborne_q.webp',
  },
  frostborne_w: {
    id: 'frostborne_w',
    name: 'Frost Nova',
    description: 'Explodes with cold energy, damaging and freezing nearby enemies briefly.',
    slot: 'W',
    targetType: 'self',
    damageType: 'magical',
    manaCost: [70, 75, 80, 85, 90],
    cooldown: [14, 13, 12, 11, 10],
    castTime: 0,
    range: 0,
    radius: 350,
    baseDamage: [70, 110, 150, 190, 230],
    scalingAP: 0.55,
    iconPath: '/assets/abilities/frostborne_w.webp',
  },
  frostborne_e: {
    id: 'frostborne_e',
    name: 'Glacial Path',
    description: 'Creates a path of ice, gaining movement speed and leaving a slowing trail.',
    slot: 'E',
    targetType: 'direction',
    damageType: null,
    manaCost: [50, 50, 50, 50, 50],
    cooldown: [16, 14, 12, 10, 8],
    castTime: 0,
    range: 500,
    iconPath: '/assets/abilities/frostborne_e.webp',
  },
  frostborne_r: {
    id: 'frostborne_r',
    name: 'Absolute Zero',
    description: 'Channels to freeze all enemies in a large area, dealing damage over time.',
    slot: 'R',
    targetType: 'area',
    damageType: 'magical',
    manaCost: [100, 100, 100],
    cooldown: [120, 100, 80],
    castTime: 1.5,
    range: 600,
    radius: 500,
    baseDamage: [250, 400, 550],
    scalingAP: 1.0,
    iconPath: '/assets/abilities/frostborne_r.webp',
  },

  // =============================================================================
  // GRIMJAW - Warrior (Human)
  // =============================================================================
  grimjaw_q: {
    id: 'grimjaw_q',
    name: 'Cleave',
    description: 'Swings axe in a wide arc, damaging all enemies in front.',
    slot: 'Q',
    targetType: 'direction',
    damageType: 'physical',
    manaCost: [30, 35, 40, 45, 50],
    cooldown: [6, 5.5, 5, 4.5, 4],
    castTime: 0.2,
    range: 300,
    radius: 200,
    baseDamage: [50, 85, 120, 155, 190],
    scalingAD: 0.8,
    iconPath: '/assets/abilities/grimjaw_q.webp',
  },
  grimjaw_w: {
    id: 'grimjaw_w',
    name: 'Blood Rage',
    description: 'Enters a rage, gaining attack damage and lifesteal based on missing health.',
    slot: 'W',
    targetType: 'self',
    damageType: null,
    manaCost: [40, 40, 40, 40, 40],
    cooldown: [16, 15, 14, 13, 12],
    castTime: 0,
    range: 0,
    iconPath: '/assets/abilities/grimjaw_w.webp',
  },
  grimjaw_e: {
    id: 'grimjaw_e',
    name: 'Savage Leap',
    description: 'Leaps to target location, dealing damage and slowing enemies on landing.',
    slot: 'E',
    targetType: 'point',
    damageType: 'physical',
    manaCost: [50, 55, 60, 65, 70],
    cooldown: [14, 13, 12, 11, 10],
    castTime: 0,
    range: 600,
    radius: 250,
    baseDamage: [60, 100, 140, 180, 220],
    scalingAD: 0.6,
    iconPath: '/assets/abilities/grimjaw_e.webp',
  },
  grimjaw_r: {
    id: 'grimjaw_r',
    name: 'Unstoppable Fury',
    description: 'Becomes immune to CC and gains massive attack speed, but takes increased damage.',
    slot: 'R',
    targetType: 'self',
    damageType: null,
    manaCost: [100, 100, 100],
    cooldown: [100, 85, 70],
    castTime: 0,
    range: 0,
    iconPath: '/assets/abilities/grimjaw_r.webp',
  },

  // =============================================================================
  // ZEPHYR - Healer (Mystical)
  // =============================================================================
  zephyr_q: {
    id: 'zephyr_q',
    name: 'Gust',
    description: 'Sends a gust of wind that heals ally or damages enemy on contact.',
    slot: 'Q',
    targetType: 'unit',
    damageType: 'magical',
    manaCost: [45, 50, 55, 60, 65],
    cooldown: [4, 3.5, 3, 2.5, 2],
    castTime: 0.15,
    range: 650,
    baseDamage: [50, 85, 120, 155, 190],
    scalingAP: 0.55,
    iconPath: '/assets/abilities/zephyr_q.webp',
  },
  zephyr_w: {
    id: 'zephyr_w',
    name: 'Tailwind',
    description: 'Grants target ally bonus movement speed and removes slows.',
    slot: 'W',
    targetType: 'unit',
    damageType: null,
    manaCost: [50, 55, 60, 65, 70],
    cooldown: [12, 11, 10, 9, 8],
    castTime: 0,
    range: 700,
    iconPath: '/assets/abilities/zephyr_w.webp',
  },
  zephyr_e: {
    id: 'zephyr_e',
    name: 'Cyclone',
    description: 'Creates a small cyclone that knocks up and damages enemies in the area.',
    slot: 'E',
    targetType: 'area',
    damageType: 'magical',
    manaCost: [70, 75, 80, 85, 90],
    cooldown: [16, 15, 14, 13, 12],
    castTime: 0.25,
    range: 750,
    radius: 250,
    baseDamage: [60, 100, 140, 180, 220],
    scalingAP: 0.5,
    iconPath: '/assets/abilities/zephyr_e.webp',
  },
  zephyr_r: {
    id: 'zephyr_r',
    name: 'Eye of the Storm',
    description: 'Creates a protective barrier of wind around allies, healing and shielding them.',
    slot: 'R',
    targetType: 'area',
    damageType: null,
    manaCost: [100, 100, 100],
    cooldown: [140, 120, 100],
    castTime: 0.3,
    range: 800,
    radius: 450,
    baseDamage: [150, 250, 350], // Healing
    scalingAP: 0.5,
    iconPath: '/assets/abilities/zephyr_r.webp',
  },

  // =============================================================================
  // VALERIA - Tank (Human)
  // =============================================================================
  valeria_q: {
    id: 'valeria_q',
    name: 'Divine Smite',
    description: 'Strikes with holy power, dealing magic damage and marking the enemy.',
    slot: 'Q',
    targetType: 'unit',
    damageType: 'magical',
    manaCost: [40, 45, 50, 55, 60],
    cooldown: [7, 6.5, 6, 5.5, 5],
    castTime: 0.15,
    range: 200,
    baseDamage: [60, 95, 130, 165, 200],
    scalingAP: 0.5,
    scalingAD: 0.4,
    iconPath: '/assets/abilities/valeria_q.webp',
  },
  valeria_w: {
    id: 'valeria_w',
    name: 'Aegis of Light',
    description: 'Creates a protective aura that reduces damage taken by nearby allies.',
    slot: 'W',
    targetType: 'self',
    damageType: null,
    manaCost: [60, 65, 70, 75, 80],
    cooldown: [18, 17, 16, 15, 14],
    castTime: 0,
    range: 0,
    radius: 400,
    iconPath: '/assets/abilities/valeria_w.webp',
  },
  valeria_e: {
    id: 'valeria_e',
    name: 'Righteous Charge',
    description: 'Charges forward, stunning the first enemy champion hit.',
    slot: 'E',
    targetType: 'direction',
    damageType: 'physical',
    manaCost: [70, 70, 70, 70, 70],
    cooldown: [14, 13, 12, 11, 10],
    castTime: 0,
    range: 650,
    baseDamage: [80, 120, 160, 200, 240],
    scalingAD: 0.5,
    iconPath: '/assets/abilities/valeria_e.webp',
  },
  valeria_r: {
    id: 'valeria_r',
    name: 'Divine Intervention',
    description: 'Makes target ally invulnerable for a short duration.',
    slot: 'R',
    targetType: 'unit',
    damageType: null,
    manaCost: [100, 100, 100],
    cooldown: [150, 130, 110],
    castTime: 0,
    range: 800,
    iconPath: '/assets/abilities/valeria_r.webp',
  },

  // =============================================================================
  // SCOURGE - Warrior (Mystical)
  // =============================================================================
  scourge_q: {
    id: 'scourge_q',
    name: 'Hellfire Slash',
    description: 'Slashes with demonic claws, dealing physical and magic damage.',
    slot: 'Q',
    targetType: 'direction',
    damageType: 'physical',
    manaCost: [35, 40, 45, 50, 55],
    cooldown: [5, 4.5, 4, 3.5, 3],
    castTime: 0.1,
    range: 300,
    radius: 180,
    baseDamage: [40, 75, 110, 145, 180],
    scalingAD: 0.7,
    scalingAP: 0.3,
    iconPath: '/assets/abilities/scourge_q.webp',
  },
  scourge_w: {
    id: 'scourge_w',
    name: 'Demon Wings',
    description: 'Spreads demonic wings, dashing forward and gaining armor shred on attacks.',
    slot: 'W',
    targetType: 'direction',
    damageType: null,
    manaCost: [50, 50, 50, 50, 50],
    cooldown: [12, 11, 10, 9, 8],
    castTime: 0,
    range: 500,
    iconPath: '/assets/abilities/scourge_w.webp',
  },
  scourge_e: {
    id: 'scourge_e',
    name: 'Soul Rend',
    description: 'Rips at enemy soul, dealing damage and healing for a portion.',
    slot: 'E',
    targetType: 'unit',
    damageType: 'magical',
    manaCost: [60, 65, 70, 75, 80],
    cooldown: [10, 9, 8, 7, 6],
    castTime: 0.2,
    range: 400,
    baseDamage: [70, 115, 160, 205, 250],
    scalingAP: 0.6,
    iconPath: '/assets/abilities/scourge_e.webp',
  },
  scourge_r: {
    id: 'scourge_r',
    name: 'Infernal Form',
    description: 'Transforms into true demon form, gaining stats and AoE auto-attacks.',
    slot: 'R',
    targetType: 'self',
    damageType: null,
    manaCost: [100, 100, 100],
    cooldown: [120, 100, 80],
    castTime: 0.5,
    range: 0,
    iconPath: '/assets/abilities/scourge_r.webp',
  },

  // =============================================================================
  // HEX - Mage (Human)
  // =============================================================================
  hex_q: {
    id: 'hex_q',
    name: 'Curse Bolt',
    description: 'Fires a bolt that curses the target, dealing damage over time.',
    slot: 'Q',
    targetType: 'unit',
    damageType: 'magical',
    manaCost: [50, 55, 60, 65, 70],
    cooldown: [6, 5.5, 5, 4.5, 4],
    castTime: 0.2,
    range: 750,
    baseDamage: [60, 100, 140, 180, 220],
    scalingAP: 0.65,
    iconPath: '/assets/abilities/hex_q.webp',
  },
  hex_w: {
    id: 'hex_w',
    name: 'Weaken',
    description: 'Curses target enemy, reducing their damage dealt and armor.',
    slot: 'W',
    targetType: 'unit',
    damageType: null,
    manaCost: [60, 65, 70, 75, 80],
    cooldown: [14, 13, 12, 11, 10],
    castTime: 0.15,
    range: 700,
    iconPath: '/assets/abilities/hex_w.webp',
  },
  hex_e: {
    id: 'hex_e',
    name: 'Life Drain',
    description: 'Channels to drain life from enemy, healing self for damage dealt.',
    slot: 'E',
    targetType: 'unit',
    damageType: 'magical',
    manaCost: [70, 75, 80, 85, 90],
    cooldown: [12, 11, 10, 9, 8],
    castTime: 0,
    range: 600,
    baseDamage: [80, 130, 180, 230, 280],
    scalingAP: 0.7,
    iconPath: '/assets/abilities/hex_e.webp',
  },
  hex_r: {
    id: 'hex_r',
    name: 'Polymorph',
    description: 'Transforms enemy into a harmless creature, silencing and slowing them.',
    slot: 'R',
    targetType: 'unit',
    damageType: null,
    manaCost: [100, 100, 100],
    cooldown: [140, 120, 100],
    castTime: 0.3,
    range: 650,
    iconPath: '/assets/abilities/hex_r.webp',
  },
};

export const ABILITY_IDS = Object.keys(ABILITIES);

export function getAbilitiesForHero(heroId: string): AbilityDefinition[] {
  return [
    ABILITIES[`${heroId}_q`],
    ABILITIES[`${heroId}_w`],
    ABILITIES[`${heroId}_e`],
    ABILITIES[`${heroId}_r`],
  ].filter(Boolean);
}

export function getAbilityById(abilityId: string): AbilityDefinition | undefined {
  return ABILITIES[abilityId];
}
