import type { HeroDefinition } from '../types/hero';

export const HEROES: Record<string, HeroDefinition> = {
  ironclad: {
    id: 'ironclad',
    name: 'Ironclad',
    title: 'The Unbreakable Shield',
    faction: 'human',
    role: 'tank',
    attackType: 'melee',
    difficulty: 1,
    baseStats: {
      maxHealth: 700,
      maxMana: 250,
      healthRegen: 3.5,
      manaRegen: 1.0,
      attackDamage: 55,
      attackSpeed: 0.8,
      attackRange: 150,
      spellPower: 0,
      armor: 35,
      magicResist: 25,
      moveSpeed: 310,
    },
    scaling: {
      healthPerLevel: 95,
      manaPerLevel: 35,
      healthRegenPerLevel: 0.8,
      manaRegenPerLevel: 0.3,
      attackDamagePerLevel: 3.5,
      armorPerLevel: 4.0,
      magicResistPerLevel: 1.5,
    },
    abilities: ['ironclad_q', 'ironclad_w', 'ironclad_e', 'ironclad_r'],
    shortDescription: 'A stalwart defender who shields allies and disrupts enemies.',
    lore: `Forged in the furnaces of the Northern Citadel, Commander Aldric earned the name "Ironclad"
after holding the Gates of Dorn against a thousand demon-kin for three days and nights.
His enchanted armor, blessed by the last war-priests, makes him nearly impervious to magical assault.
Now he stands as humanity's bulwark against the mystical forces that threaten to consume the realm.`,
    splashArt: '/assets/heroes/ironclad/splash.webp',
    modelPath: '/assets/heroes/ironclad/model.glb',
  },

  pyralis: {
    id: 'pyralis',
    name: 'Pyralis',
    title: 'The Flame Incarnate',
    faction: 'mystical',
    role: 'mage',
    attackType: 'ranged',
    difficulty: 2,
    baseStats: {
      maxHealth: 480,
      maxMana: 450,
      healthRegen: 1.5,
      manaRegen: 3.5,
      attackDamage: 42,
      attackSpeed: 0.7,
      attackRange: 550,
      spellPower: 1.0,
      armor: 15,
      magicResist: 30,
      moveSpeed: 330,
    },
    scaling: {
      healthPerLevel: 75,
      manaPerLevel: 55,
      healthRegenPerLevel: 0.4,
      manaRegenPerLevel: 0.8,
      attackDamagePerLevel: 2.5,
      armorPerLevel: 2.5,
      magicResistPerLevel: 2.0,
    },
    abilities: ['pyralis_q', 'pyralis_w', 'pyralis_e', 'pyralis_r'],
    shortDescription: 'A devastating fire mage who incinerates foes from afar.',
    lore: `Born from the eternal flames of Mount Valdris, Pyralis is not merely a wielder of fire—she IS fire.
When the Mystical Council foresaw the human threat, they awakened this primordial elemental to serve
as their instrument of destruction. Each spell she casts draws from the world's molten core,
leaving nothing but ash in her wake. She feels no remorse, only the burning desire to consume.`,
    splashArt: '/assets/heroes/pyralis/splash.webp',
    modelPath: '/assets/heroes/pyralis/model.glb',
  },

  bladewarden: {
    id: 'bladewarden',
    name: 'Bladewarden',
    title: 'The Storm of Steel',
    faction: 'human',
    role: 'warrior',
    attackType: 'melee',
    difficulty: 2,
    baseStats: {
      maxHealth: 580,
      maxMana: 300,
      healthRegen: 2.5,
      manaRegen: 1.5,
      attackDamage: 62,
      attackSpeed: 1.0,
      attackRange: 175,
      spellPower: 0,
      armor: 25,
      magicResist: 20,
      moveSpeed: 345,
    },
    scaling: {
      healthPerLevel: 85,
      manaPerLevel: 40,
      healthRegenPerLevel: 0.6,
      manaRegenPerLevel: 0.4,
      attackDamagePerLevel: 4.0,
      armorPerLevel: 3.0,
      magicResistPerLevel: 1.5,
    },
    abilities: ['bladewarden_q', 'bladewarden_w', 'bladewarden_e', 'bladewarden_r'],
    shortDescription: 'A relentless duelist who overwhelms enemies with swift combos.',
    lore: `Marcus Thorne was once the realm's most celebrated tournament champion,
undefeated in a thousand bouts. When the mystical forces burned his village and slaughtered his family,
his blade found a new purpose. Training in forbidden sword techniques passed down from an ancient order,
he became the Bladewarden—a one-man army capable of cutting through magic itself.
His twin swords, Mercy and Vengeance, have not known rest since.`,
    splashArt: '/assets/heroes/bladewarden/splash.webp',
    modelPath: '/assets/heroes/bladewarden/model.glb',
  },

  sylara: {
    id: 'sylara',
    name: 'Sylara',
    title: 'The Lifebringer',
    faction: 'mystical',
    role: 'healer',
    attackType: 'ranged',
    difficulty: 1,
    baseStats: {
      maxHealth: 500,
      maxMana: 400,
      healthRegen: 2.0,
      manaRegen: 3.0,
      attackDamage: 38,
      attackSpeed: 0.65,
      attackRange: 500,
      spellPower: 0.8,
      armor: 18,
      magicResist: 35,
      moveSpeed: 325,
    },
    scaling: {
      healthPerLevel: 80,
      manaPerLevel: 50,
      healthRegenPerLevel: 0.5,
      manaRegenPerLevel: 0.7,
      attackDamagePerLevel: 2.0,
      armorPerLevel: 2.5,
      magicResistPerLevel: 2.5,
    },
    abilities: ['sylara_q', 'sylara_w', 'sylara_e', 'sylara_r'],
    shortDescription: 'A graceful healer who sustains allies and cleanses afflictions.',
    lore: `Deep within the Everbloom Grove, where life magic flows like rivers of light,
Sylara tended to the wounded spirits of the forest for millennia.
When the war between realms began poisoning the land itself,
she emerged from her sanctuary to heal a world bleeding from a thousand wounds.
Her touch can mend shattered bones and purify corrupted souls,
but those who mistake her gentleness for weakness learn that life magic can also choke and bind.`,
    splashArt: '/assets/heroes/sylara/splash.webp',
    modelPath: '/assets/heroes/sylara/model.glb',
  },

  // =============================================================================
  // NEW HEROES (10 additional)
  // =============================================================================

  nightshade: {
    id: 'nightshade',
    name: 'Nightshade',
    title: 'The Shadow Reaper',
    faction: 'mystical',
    role: 'assassin',
    attackType: 'melee',
    difficulty: 3,
    baseStats: {
      maxHealth: 520,
      maxMana: 320,
      healthRegen: 2.0,
      manaRegen: 2.0,
      attackDamage: 58,
      attackSpeed: 1.1,
      attackRange: 150,
      spellPower: 0.3,
      armor: 20,
      magicResist: 25,
      moveSpeed: 355,
    },
    scaling: {
      healthPerLevel: 78,
      manaPerLevel: 38,
      healthRegenPerLevel: 0.5,
      manaRegenPerLevel: 0.5,
      attackDamagePerLevel: 3.8,
      armorPerLevel: 2.8,
      magicResistPerLevel: 1.5,
    },
    abilities: ['nightshade_q', 'nightshade_w', 'nightshade_e', 'nightshade_r'],
    shortDescription: 'A deadly assassin who strikes from the shadows.',
    lore: `Born in the lightless depths of the Shadow Realm, Nightshade was trained from infancy
to be the perfect killer. She can slip between shadows as easily as mortals walk through doors,
appearing behind her victims before they even sense danger. The Mystical Council uses her
to eliminate key human commanders, and her blade has never failed to find its mark.
They say the last thing her targets see is their own shadow turning against them.`,
    splashArt: '/assets/heroes/nightshade/splash.webp',
    modelPath: '/assets/heroes/nightshade/model.glb',
  },

  vex: {
    id: 'vex',
    name: 'Vex',
    title: 'The Venomous Hunter',
    faction: 'human',
    role: 'assassin',
    attackType: 'melee',
    difficulty: 3,
    baseStats: {
      maxHealth: 540,
      maxMana: 280,
      healthRegen: 2.2,
      manaRegen: 1.8,
      attackDamage: 56,
      attackSpeed: 1.15,
      attackRange: 150,
      spellPower: 0,
      armor: 22,
      magicResist: 22,
      moveSpeed: 350,
    },
    scaling: {
      healthPerLevel: 80,
      manaPerLevel: 35,
      healthRegenPerLevel: 0.55,
      manaRegenPerLevel: 0.45,
      attackDamagePerLevel: 3.6,
      armorPerLevel: 3.0,
      magicResistPerLevel: 1.5,
    },
    abilities: ['vex_q', 'vex_w', 'vex_e', 'vex_r'],
    shortDescription: 'An acrobatic bounty hunter wielding poisoned blades.',
    lore: `Vex grew up in the slums of Port Ashfall, surviving by stealing and fighting.
When the mystical invasion killed everyone she knew, she channeled her rage into becoming
the most feared bounty hunter in the realm. Her twin daggers are coated with a paralytic venom
she brews herself, and her acrobatic fighting style makes her nearly impossible to hit.
For the right price, she'll hunt anyone—but mystical creatures? Those she kills for free.`,
    splashArt: '/assets/heroes/vex/splash.webp',
    modelPath: '/assets/heroes/vex/model.glb',
  },

  thornweaver: {
    id: 'thornweaver',
    name: 'Thornweaver',
    title: 'The Living Fortress',
    faction: 'mystical',
    role: 'tank',
    attackType: 'melee',
    difficulty: 2,
    baseStats: {
      maxHealth: 720,
      maxMana: 280,
      healthRegen: 4.0,
      manaRegen: 1.2,
      attackDamage: 52,
      attackSpeed: 0.75,
      attackRange: 175,
      spellPower: 0.2,
      armor: 38,
      magicResist: 28,
      moveSpeed: 305,
    },
    scaling: {
      healthPerLevel: 100,
      manaPerLevel: 32,
      healthRegenPerLevel: 0.9,
      manaRegenPerLevel: 0.25,
      attackDamagePerLevel: 3.2,
      armorPerLevel: 4.5,
      magicResistPerLevel: 1.8,
    },
    abilities: ['thornweaver_q', 'thornweaver_w', 'thornweaver_e', 'thornweaver_r'],
    shortDescription: 'An ancient tree guardian covered in thorny armor.',
    lore: `Thornweaver was once a peaceful druid who merged with an ancient oak to save it from
human loggers. Over centuries, the fusion transformed him into something neither plant nor man—
a walking fortress of bark and thorns. He feels the pain of every tree felled, every forest burned,
and has sworn to protect the natural world by any means necessary. His thorny exterior
reflects damage back to attackers, making him a nightmare to engage in close combat.`,
    splashArt: '/assets/heroes/thornweaver/splash.webp',
    modelPath: '/assets/heroes/thornweaver/model.glb',
  },

  magnus: {
    id: 'magnus',
    name: 'Magnus',
    title: 'The Gravity Mage',
    faction: 'human',
    role: 'mage',
    attackType: 'ranged',
    difficulty: 3,
    baseStats: {
      maxHealth: 460,
      maxMana: 480,
      healthRegen: 1.4,
      manaRegen: 3.8,
      attackDamage: 40,
      attackSpeed: 0.68,
      attackRange: 525,
      spellPower: 1.1,
      armor: 14,
      magicResist: 32,
      moveSpeed: 325,
    },
    scaling: {
      healthPerLevel: 72,
      manaPerLevel: 58,
      healthRegenPerLevel: 0.38,
      manaRegenPerLevel: 0.85,
      attackDamagePerLevel: 2.2,
      armorPerLevel: 2.3,
      magicResistPerLevel: 2.2,
    },
    abilities: ['magnus_q', 'magnus_w', 'magnus_e', 'magnus_r'],
    shortDescription: 'A brilliant archmage who manipulates gravity itself.',
    lore: `Professor Magnus spent decades studying the fundamental forces of the universe
at the Royal Academy of Arcane Sciences. When he finally unlocked the secrets of gravity magic,
the Mystical Council saw him as humanity's greatest threat and destroyed the academy.
Now Magnus uses his powers to crush the mystical invaders with the very force that holds
worlds together. He can create black holes, reverse gravity, and turn his enemies' mass against them.`,
    splashArt: '/assets/heroes/magnus/splash.webp',
    modelPath: '/assets/heroes/magnus/model.glb',
  },

  frostborne: {
    id: 'frostborne',
    name: 'Frostborne',
    title: 'The Frozen Heart',
    faction: 'mystical',
    role: 'mage',
    attackType: 'ranged',
    difficulty: 2,
    baseStats: {
      maxHealth: 470,
      maxMana: 440,
      healthRegen: 1.6,
      manaRegen: 3.4,
      attackDamage: 44,
      attackSpeed: 0.72,
      attackRange: 550,
      spellPower: 0.95,
      armor: 16,
      magicResist: 28,
      moveSpeed: 335,
    },
    scaling: {
      healthPerLevel: 74,
      manaPerLevel: 52,
      healthRegenPerLevel: 0.42,
      manaRegenPerLevel: 0.75,
      attackDamagePerLevel: 2.4,
      armorPerLevel: 2.4,
      magicResistPerLevel: 2.0,
    },
    abilities: ['frostborne_q', 'frostborne_w', 'frostborne_e', 'frostborne_r'],
    shortDescription: 'An ice elemental who freezes and shatters foes.',
    lore: `From the eternal glaciers of the North came Frostborne, an elemental spirit of pure cold.
Unlike fire, which burns hot with passion, ice is patient and methodical. Frostborne
encases enemies in frost, slowing their movements and thoughts until they become ice sculptures.
The Mystical Council awakened her to counter humanity's fire mages, and she has proven
devastatingly effective. Her presence alone drops the temperature, and her touch means death.`,
    splashArt: '/assets/heroes/frostborne/splash.webp',
    modelPath: '/assets/heroes/frostborne/model.glb',
  },

  grimjaw: {
    id: 'grimjaw',
    name: 'Grimjaw',
    title: 'The Berserker',
    faction: 'human',
    role: 'warrior',
    attackType: 'melee',
    difficulty: 1,
    baseStats: {
      maxHealth: 620,
      maxMana: 200,
      healthRegen: 3.0,
      manaRegen: 0.8,
      attackDamage: 68,
      attackSpeed: 0.9,
      attackRange: 175,
      spellPower: 0,
      armor: 28,
      magicResist: 18,
      moveSpeed: 340,
    },
    scaling: {
      healthPerLevel: 92,
      manaPerLevel: 25,
      healthRegenPerLevel: 0.7,
      manaRegenPerLevel: 0.2,
      attackDamagePerLevel: 4.5,
      armorPerLevel: 3.5,
      magicResistPerLevel: 1.2,
    },
    abilities: ['grimjaw_q', 'grimjaw_w', 'grimjaw_e', 'grimjaw_r'],
    shortDescription: 'A brutal barbarian who grows stronger as he bleeds.',
    lore: `Grimjaw hails from the savage Northern Tribes, where only the strongest survive.
He earned his name by ripping out a demon's jaw with his bare hands during a raid.
His fighting style is simple but terrifying—he charges into battle swinging a massive axe,
getting stronger and more dangerous as he takes damage. Pain only fuels his rage,
and his war cry alone has been known to break enemy morale.`,
    splashArt: '/assets/heroes/grimjaw/splash.webp',
    modelPath: '/assets/heroes/grimjaw/model.glb',
  },

  zephyr: {
    id: 'zephyr',
    name: 'Zephyr',
    title: 'The Wind Spirit',
    faction: 'mystical',
    role: 'healer',
    attackType: 'ranged',
    difficulty: 2,
    baseStats: {
      maxHealth: 480,
      maxMana: 420,
      healthRegen: 1.8,
      manaRegen: 3.2,
      attackDamage: 36,
      attackSpeed: 0.7,
      attackRange: 525,
      spellPower: 0.85,
      armor: 15,
      magicResist: 30,
      moveSpeed: 340,
    },
    scaling: {
      healthPerLevel: 76,
      manaPerLevel: 48,
      healthRegenPerLevel: 0.45,
      manaRegenPerLevel: 0.7,
      attackDamagePerLevel: 1.8,
      armorPerLevel: 2.2,
      magicResistPerLevel: 2.4,
    },
    abilities: ['zephyr_q', 'zephyr_w', 'zephyr_e', 'zephyr_r'],
    shortDescription: 'A wind spirit who accelerates allies and disrupts enemies.',
    lore: `Zephyr is the playful spirit of the western winds, usually content to dance through
meadows and carry seeds across continents. But when the war between realms threatened to
stagnate the very air, she joined the mystical forces to restore balance.
Her winds can carry allies to safety, speed their movements, or knock enemies off their feet.
Unlike the violent Pyralis, Zephyr prefers to support and protect rather than destroy.`,
    splashArt: '/assets/heroes/zephyr/splash.webp',
    modelPath: '/assets/heroes/zephyr/model.glb',
  },

  valeria: {
    id: 'valeria',
    name: 'Valeria',
    title: 'The Radiant Shield',
    faction: 'human',
    role: 'tank',
    attackType: 'melee',
    difficulty: 2,
    baseStats: {
      maxHealth: 680,
      maxMana: 300,
      healthRegen: 3.2,
      manaRegen: 1.5,
      attackDamage: 50,
      attackSpeed: 0.78,
      attackRange: 150,
      spellPower: 0.4,
      armor: 32,
      magicResist: 30,
      moveSpeed: 315,
    },
    scaling: {
      healthPerLevel: 90,
      manaPerLevel: 40,
      healthRegenPerLevel: 0.75,
      manaRegenPerLevel: 0.35,
      attackDamagePerLevel: 3.0,
      armorPerLevel: 3.8,
      magicResistPerLevel: 2.0,
    },
    abilities: ['valeria_q', 'valeria_w', 'valeria_e', 'valeria_r'],
    shortDescription: 'A holy paladin with protective auras and divine smite.',
    lore: `Lady Valeria was the High Paladin of the Order of the Radiant Dawn, sworn to protect
the innocent and vanquish evil. When the mystical forces corrupted her entire order,
she alone resisted their influence, her faith burning too bright to be extinguished.
Now she stands as humanity's spiritual defender, her holy auras shielding allies
and her blessed hammer smiting those who would harm the righteous.`,
    splashArt: '/assets/heroes/valeria/splash.webp',
    modelPath: '/assets/heroes/valeria/model.glb',
  },

  scourge: {
    id: 'scourge',
    name: 'Scourge',
    title: 'The Demon Prince',
    faction: 'mystical',
    role: 'warrior',
    attackType: 'melee',
    difficulty: 2,
    baseStats: {
      maxHealth: 600,
      maxMana: 280,
      healthRegen: 2.8,
      manaRegen: 1.4,
      attackDamage: 64,
      attackSpeed: 0.95,
      attackRange: 175,
      spellPower: 0.3,
      armor: 26,
      magicResist: 24,
      moveSpeed: 340,
    },
    scaling: {
      healthPerLevel: 88,
      manaPerLevel: 36,
      healthRegenPerLevel: 0.65,
      manaRegenPerLevel: 0.35,
      attackDamagePerLevel: 4.2,
      armorPerLevel: 3.2,
      magicResistPerLevel: 1.8,
    },
    abilities: ['scourge_q', 'scourge_w', 'scourge_e', 'scourge_r'],
    shortDescription: 'A demon prince with devastating area attacks.',
    lore: `Scourge was once a prince of the demon realm, but his thirst for power led him to
betray his own kind and join the Mystical Council. In exchange for his service,
they granted him the ability to manifest in the mortal realm permanently.
His demonic flames burn with hellfire, and his massive claws can cleave through
multiple enemies at once. He fights not for ideology, but for the sheer joy of destruction.`,
    splashArt: '/assets/heroes/scourge/splash.webp',
    modelPath: '/assets/heroes/scourge/model.glb',
  },

  hex: {
    id: 'hex',
    name: 'Hex',
    title: 'The Curse Weaver',
    faction: 'human',
    role: 'mage',
    attackType: 'ranged',
    difficulty: 3,
    baseStats: {
      maxHealth: 450,
      maxMana: 460,
      healthRegen: 1.3,
      manaRegen: 3.6,
      attackDamage: 38,
      attackSpeed: 0.65,
      attackRange: 575,
      spellPower: 1.0,
      armor: 12,
      magicResist: 34,
      moveSpeed: 330,
    },
    scaling: {
      healthPerLevel: 70,
      manaPerLevel: 55,
      healthRegenPerLevel: 0.35,
      manaRegenPerLevel: 0.8,
      attackDamagePerLevel: 2.0,
      armorPerLevel: 2.0,
      magicResistPerLevel: 2.3,
    },
    abilities: ['hex_q', 'hex_w', 'hex_e', 'hex_r'],
    shortDescription: 'A witch who weakens enemies with curses and hexes.',
    lore: `The witch known only as Hex was burned at the stake three times—and returned each time,
angrier than before. Her mastery of curse magic lets her weaken enemies, drain their strength,
and turn their own powers against them. The Mystical Council offered her immortality
to join them, but she refused; she fights for humanity not out of love,
but because she despises being told what to do. Her curses are legendary,
and even her allies keep their distance.`,
    splashArt: '/assets/heroes/hex/splash.webp',
    modelPath: '/assets/heroes/hex/model.glb',
  },
};

export const HERO_IDS = Object.keys(HEROES);

export const HEROES_BY_FACTION = {
  mystical: Object.values(HEROES).filter((h) => h.faction === 'mystical'),
  human: Object.values(HEROES).filter((h) => h.faction === 'human'),
};

export const HEROES_BY_ROLE = {
  tank: Object.values(HEROES).filter((h) => h.role === 'tank'),
  mage: Object.values(HEROES).filter((h) => h.role === 'mage'),
  warrior: Object.values(HEROES).filter((h) => h.role === 'warrior'),
  healer: Object.values(HEROES).filter((h) => h.role === 'healer'),
  assassin: Object.values(HEROES).filter((h) => h.role === 'assassin'),
};
